['LA', 'Senkeidaisuugaku', 'CreamdelaCream.tex', '/Users/zechen/Documents/PhantasiaAcademia/Algebra/LinearAlgebra/Note', 'PLACEHOLDER', 'PLACEHOLDER']
Traceback (most recent call last):
  File "/Users/zechen/Documents/PhantasiaAcademia/getsubjects.py", line 29, in <module>
    sections_file = open('/Users/zechen/Documents/PhantasiaAcademia/' + subject_dir + '/sections', 'r')
IOError: [Errno 2] No such file or directory: '/Users/zechen/Documents/PhantasiaAcademia/Algebra/LinearAlgebra/sections'
